### ISSUE TITLE
uninitialized value line 151

### ISSUE THREAD

**Issue by ferrellb** [dnasko/dna_pola_762_caller#2]
My first attempt to run E. coli related info to determine position on the E. coli reference of the start position of query sequences - get repeated message while running:
Use of initialized value $results[1] in join or string at ecoli_related_info.pl line 151.

**Comment by dnasko** [comment]
Interesting. Can you email me the input file you're using?

**Comment by dnasko** [comment]
I've resolved the error, and I believe it has to do with instances where the first peptide of a query occurs before the first peptide of the _E. coli_ reference. e.g.
_E. coli_:  -----MC--HL ...
Query: M-----C---HL...

Need to think about how we wan to handle these cases. Right now it would say "the first peptide of your query aligns with position 0 of _E. coli_". I suppose a more accurate answer would be that it matches with position -1 ? Not sure how important it is to capture how negative it is. Probably sufficient to know that it's starting before _E. coli_ and that's it.

**Comment by dnasko** [comment]
This issue seems to be resolved. If it crops up again I will reopen it.
